def normalize(text):
    CONTROLS = {
        '\u0001', '\u0002', '\u0003', '\u0004', '\u0005', '\u0006', '\u0007', '\u0008', '\u000e', '\u000f', '\u0011',
        '\u0012', '\u0013', '\u0014', '\u0015', '\u0016', '\u0017', '\u0018', '\u0019', '\u001a', '\u001b', '\u200b',
    }
    for control in CONTROLS:
        text = text.replace(control, '')
    text = text.replace('\u000b', ' ').replace('\u000c', ' ').replace(u'\u0085', ' ')
    text = text.replace('\u00ad', '').replace('\u2028', '\n').replace('\u2029', '\n')
    text = re.sub(r'[‐‑⁃‒–—−－⁻―]', '-', text)
    text = re.sub(r'[+＋⁺]', '+', text) 
    text = re.sub(r'[/⁄∕]', '/', text)
    text = re.sub(r'[~˜⁓∼∽∿〜～]', '~', text)
    text = re.sub(r"['’՚Ꞌꞌ＇'‘’‛`´′‵]", "'", text)
    text = re.sub(r'["“”„‟″‶‴‷⁗＂˝]', '"', text)
    text = re.sub(r"[‚]", ",", text)
    text = re.sub(r"[〓]", "=", text)
    text = re.sub(r"[㎞]", "km", text)
    text = re.sub(r"[㎏]", "kg", text)
    text = re.sub(r"[㎜]", "mm", text)
    text = re.sub(r"[㎝]", "cm", text)
    text = re.sub(r"[㎟]", "mm2", text) 
    text = re.sub(r"[㎣]", "mm3", text)
    text = re.sub(r"[㎡]", "m2", text)
    text = re.sub(r"[㎢]", "km2", text)
    text = re.sub(r"[㏊]", "ha", text)
    text = re.sub(r"[㏈]", "dB", text)
    text = re.sub(r"[㎉]", "kcal", text)
    text = re.sub(r"[㎈]", "cal", text)
    text = re.sub(r"[㎖]", "ml", text)
    text = re.sub(r"[ℓ]", "l", text)
    text = re.sub(r"[㎛]", "μm", text)
    text = re.sub(r"[㎕]", "μl", text)
    text = re.sub(r"[《『「]", "<", text)
    text = re.sub(r"[》」』]", ">", text)
    text = re.sub(r"[【]", "[", text)
    text = re.sub(r"[】]", "]", text)
    text = text.replace('...','…')
    text = re.sub(r'[◇■○◆◎□●]',' ● ',text)
    text = re.sub(r'[▼▽△▲]', ' ▲ ', text)
    text = re.sub(r'[▷▶]', ' ▶ ', text)
    text = text.replace('  ',' ')
    text = text.replace('  ',' ')
    return text