# 기타, DT(시간, 날짜), QT(수량), URL, 이메일 등은 제외
valid_ner_code = {
    'PS_NAME': '인물',
    'PS_CHARACTER': '캐랙터',
    'PS_PET': '반려동물',
    'FD_SCIENCE': '과학',
    'FD_SOCIAL_SCIENCE': '사회과학',
    'FD_MEDICINE': '의학',
    'FD_ART': '예술',
    'FD_HUMANITIES': '인문학',
    'TR_SCIENCE': '과학',
    'TR_SOCIAL_SCIENCE': '사회과학',
    'TR_MEDICINE': '의학',
    'TR_ART': '예술',
    'TR_HUMANITIES': '인문학',
    'AF_BUILDING': '건물',
    'AF_CULTURAL_ASSET': '문화재',
    'AF_ROAD': '도로, 철도',
    'AF_TRANSPORT': '교통수단, 놀이기구',
    'AF_MUSICAL_INSTRUMENT': '악기',
    'AF_WEAPON': '무기',
    'AF_ART_WORKS': '작품',
    'AF_WARES': '상품',
    'OGG_ECONOMY': '경제',
    'OGG_EDUCATION': '교육',
    'OGG_MILITARY': '군사',
    'OGG_MEDIA': '미디어 방송',
    'OGG_SPORTS': '스포츠',
    'OGG_ART': '예술',
    'OGG_MEDICINE': '의학 의료',
    'OGG_RELIGION': '종교',
    'OGG_SCIENCE': '과학',
    'OGG_LIBRARY': '도서관',
    'OGG_LAW': '법률',
    'OGG_POLITICS': '정부 행정',
    'OGG_FOOD': '음식',
    'OGG_HOTEL': '호텔',
    'LCP_COUNTRY': '국가',
    'LCP_PROVINCE': '도, 주',
    'LCP_COUNTY': '군, 면, 동',
    'LCP_CITY': '도시',
    'LCP_CAPITALCITY': '수도',
    'LCG_RIVER': '강, 호수',
    'LCG_OCEAN': '바다',
    'LCG_BAY': '반도, 만',
    'LCG_MOUNTAIN': '산 ',
    'LCG_ISLAND': '섬',
    'LCG_CONTINENT': '대륙',
    'LC_SPACE': '천체',
    'CV_CULTURE': '문명, 혁명',
    'CV_TRIBE': '민족, 종족',
    'CV_LANGUAGE': '언어',
    'CV_POLICY': '제도, 정책',
    'CV_LAW': '법률',
    'CV_CURRENCY': '통화',
    'CV_TAX': '조세',
    'CV_FUNDS': '연금, 기금',
    'CV_ART': '예술분류',
    'CV_SPORTS': '스포츠, 레포츠, 레저',
    'CV_SPORTS_POSITION': '스포츠포지션',
    'CV_SPORTS_INST': '스포츠용품',
    'CV_PRIZE': '상, 훈장',
    'CV_RELATION': '가족관계',
    'CV_OCCUPATION': '직업',
    'CV_POSITION': '직위, 직책',
    'CV_FOOD': '음식 식재료',
    'CV_DRINK': '음료, 술',
    'CV_FOOD_STYLE': '음식유형',
    'CV_CLOTHING': '의복, 섬유',
    'CV_BUILDING_TYPE': '건축양식',
    'EV_ACTIVITY': '사회운동, 선언',
    'EV_WAR_REVOLUTION': '전쟁, 혁명, 전투',
    'EV_SPORTS': '스포츠, 레저행사',
    'EV_FESTIVAL': '축제, 영화제, 콘서트, 행사',
    'AM_INSECT': '곤충',
    'AM_BIRD': '조류',
    'AM_FISH': '어류',
    'AM_MAMMALIA': '포유류',
    'AM_AMPHIBIA': '양서류',
    'AM_REPTILIA': '파출류',
    'AM_TYPE': '동물분류',
    'AM_PART': '부분명칭',
    'PT_FRUIT': '과일',
    'PT_FLOWER': '꽃',
    'PT_TREE': '나무',
    'PT_GRASS': '풀',
    'PT_TYPE': '식물',
    'PT_PART': '부분명칭',
    'MT_ELEMENT': '원소',
    'MT_METAL': '금속',
    'MT_ROCK': '암석',
    'MT_CHEMICAL': '화학물질',
    'TM_COLOR': '색깔',
    'TM_DIRECTION': '방향',
    'TM_CLIMATE': '기후',
    'TM_SHAPE': '모양',
    'TM_CELL_TISSUE_ORGAN': '세포, 조직, 기관',
    'TMM_DISEASE': '증상, 증세, 질병',
    'TMM_DRUG': '약',
    'TMI_HW': '하드웨어',
    'TMI_SW': '소프트웨어',
    'TMI_SERVICE': 'IT서비스용어',
    'TMI_PROJECT': '프로젝트',
    'TMIG_GENRE': '게임장르',
    'TM_SPORTS': '스포츠레저기술규칙'
}